# Generated by Django 5.2.6 on 2025-09-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(help_text='Уникальный ID в рамках сценария, например step_1', max_length=50, verbose_name='ID шага')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название шага')),
                ('content', models.TextField(blank=True, help_text='Текст или промпт для GPT', verbose_name='Контент')),
                ('step_type', models.CharField(choices=[('text', 'Текст от бота'), ('question', 'Вопрос пользователю'), ('gpt', 'Генерация через GPT'), ('end', 'Конец сценария')], default='text', max_length=20, verbose_name='Тип шага')),
                ('next_step_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Следующий шаг')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scenarios.scenario')),
            ],
            options={
                'verbose_name': 'Шаг сценария',
                'verbose_name_plural': 'Шаги сценария',
                'unique_together': {('scenario', 'step_id')},
            },
        ),
    ]
